### PR TITLE
build: update cargo version 0.3.0

### PR DESCRIPTION
**Pull request by bojand**
I will tag once merged which should trigger a release.

### CODE REVIEW

**Comment by paolobarbolini** [comment]
I think I killed it in time. I thought we were supposed to put in the no_std changes as well before releasing v0.3

**Comment by bojand** [comment]
Oh sorry I think I misunderstood the plan. Thanks for catching it. 👍

**Comment by bojand** [comment]
I will revert this change and clean up the tags.

**Comment by ririsoft** [comment]
Indeed I am preparing a couple of pull requests which would be worth for a 0.3 release.
One related to the static API we already discussed in #11 and one which will allow to match an extension without a buffer (useful when you do not one to open the file)

**Comment by paolobarbolini** [comment]
Perfect. I'll send a PR for the no_std changes. I also want to refactor `(map::MatcherType, String, String, Matcher)` into a struct to make the code a bit easier to read.

**Pull request merged**
