### PR TITLE
Add support for application/x-mach-binary

### PR DESCRIPTION
**Pull request by ebkalderon**
### Added

* Add `app::is_mach()` matcher capable of detecting both 32 and 64 bit Mach-O binaries.
* Add tests with sample binaries for [x86](https://github.com/JonathanSalwan/binary-samples/blob/master/MachO-OSX-x86-ls), [x64](https://github.com/JonathanSalwan/binary-samples/blob/master/MachO-OSX-x64-ls), [PowerPC](https://github.com/JonathanSalwan/binary-samples/blob/master/MachO-OSX-ppc-openssl-1.0.1h), and [fat (x86 + PowerPC)](https://github.com/JonathanSalwan/binary-samples/blob/master/MachO-OSX-ppc-and-i386-bash).

### Changed

* Insert a new `application/x-mach-binary` entry to `MATCHER_MAP`.

I needed this for a project and had noticed that `infer` didn't support detection of Darwin Mach-O binaries, so I decided to implement this myself. Please let me know if there's anything I missed!

### CODE REVIEW

**Comment by ebkalderon** [comment]
Force-pushed the branch in order to enable the executable bit on all four sample Mach binaries.

**Comment by ebkalderon** [comment]
Pinging @bojand. Should be ready for your review now, I think! :relaxed:

**Comment by bojand** [comment]
Hello, thanks for the PR! Published [0.3.1](https://github.com/bojand/infer/releases/tag/v0.3.1).

**Comment by ebkalderon** [comment]
No worries! Thanks for the quick review and publish. :tada: Hope everything looks good.

**Pull request merged**
