### PR TITLE
Add Zstd support

### PR DESCRIPTION
**Pull request by 0x1793d1**

### CODE REVIEW

**Comment by bojand** [comment]
Hello and thanks for the PR! I am pretty busy but will get to merging and publishing this soon, hopefully later today.
One question... what is the sample file. I can't seem to decompress it fully. Perhaps just use some [lorem ipsum](https://www.lipsum.com/) text compressed as a sample test file?

**Comment by 0x1793d1** [comment]
Hi!

The sample file is just an empty sample.txt, archived using tar with zstd compression (use `zstd -d sample.tar.zst && tar xf sample.tar` to decompress).

If you prefer, I can use some lorem instead (without tar).

**Comment by bojand** [comment]
Hmm I kept getting `tar: Error opening archive: Unrecognized archive format`, but after some researching I guess that's because I am on Mac and this seems to have been compressed on Linux using gnu tar. Works with gnu-tar fine, so this is all good. I'll merge and publish later when I get some more time. Thanks again for the PR!

**Comment by 0x1793d1** [comment]
Exactly!
OK, you are welcome.

**Comment by bojand** [comment]
Hello this is now published as [0.1.4](https://crates.io/crates/infer). Probably should have published it as `0.2.0` now that I think about it... but it's not a breaking change. 🤷‍♂

**Pull request merged**
